//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Вакансии
    {
        public int ID { get; set; }
        public Nullable<int> Должность { get; set; }
        public Nullable<int> Компания { get; set; }
        public Nullable<decimal> Зарплата { get; set; }
        public string График_работы { get; set; }
        public Nullable<int> Сотрудник { get; set; }
    
        public virtual Должности Должности { get; set; }
        public virtual Компании Компании { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
